### ISSUE TITLE
rvc on Windows-Subsystem-Linux

### ISSUE THREAD

**Issue by NC-Alex** [vmware/rvc#100]
Hello,

Trying to install rvc on the "Windows-Subsystem-Linux", I have this error message:

> 
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rbvmomi/trollop (LoadError)
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /var/lib/gems/2.3.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /var/lib/gems/2.3.0/gems/rvc-1.8.0/bin/rvc:32:in `<top (required)>'
        from /usr/local/bin/rvc:23:in `load'
        from /usr/local/bin/rvc:23:in `<main>'
> 

Help please!

**Comment by xweichu** [comment]
I got this problem too... Did you get a solution? thanks a lot.
