### ISSUE TITLE
No consistent proxy usage?

### ISSUE THREAD

**Issue by f0o** [vmware/rvc#96]
Hi,

I got `http_proxy`,`https_proxy`,`HTTP_PROXY` and `HTTPS_PROXY` environment variables set but I'm unable to connect to my vsphere using `rvc vsphere.example.net`.

Any ideas?

Log:
```text
/usr/share/ruby/net/http.rb:878:in `initialize': Network is unreachable - connect(2) (Errno::ENETUNREACH)
        from /usr/share/ruby/net/http.rb:878:in `open'
        from /usr/share/ruby/net/http.rb:878:in `block in connect'
        from /usr/share/ruby/timeout.rb:66:in `timeout'
        from /usr/share/ruby/net/http.rb:877:in `connect'
        from /usr/share/ruby/net/http.rb:862:in `do_start'
        from /usr/share/ruby/net/http.rb:857:in `start'
        from /usr/local/share/gems/gems/rbvmomi-1.8.2/lib/rbvmomi/trivial_soap.rb:56:in `restart_http'
        from /usr/local/share/gems/gems/rbvmomi-1.8.2/lib/rbvmomi/trivial_soap.rb:20:in `initialize'
        from /usr/local/share/gems/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:31:in `initialize'
        from /usr/local/share/gems/gems/rvc-1.8.0/lib/rvc/modules/vsan.rb:2440:in `initialize'
        from /usr/local/share/gems/gems/rvc-1.8.0/lib/rvc/modules/vim.rb:47:in `new'
        from /usr/local/share/gems/gems/rvc-1.8.0/lib/rvc/modules/vim.rb:47:in `block in connect'
        from /usr/local/share/gems/gems/rvc-1.8.0/lib/rvc/modules/vim.rb:45:in `loop'
        from /usr/local/share/gems/gems/rvc-1.8.0/lib/rvc/modules/vim.rb:45:in `connect'
        from /usr/local/share/gems/gems/rvc-1.8.0/lib/rvc/modules/vim.rb:24:in `block in load_code'
        from /usr/local/share/gems/gems/rvc-1.8.0/bin/rvc:83:in `[]'
        from /usr/local/share/gems/gems/rvc-1.8.0/bin/rvc:83:in `block in <top (required)>'
        from /usr/local/share/gems/gems/rvc-1.8.0/bin/rvc:71:in `each'
        from /usr/local/share/gems/gems/rvc-1.8.0/bin/rvc:71:in `<top (required)>'
        from /usr/local/bin/rvc:23:in `load'
        from /usr/local/bin/rvc:23:in `<main>'
```

**Comment by dedwards-tech** [comment]
It could be a dns issue rather than proxy issue?

Also, did you make sure to set the proper port number:    myproxy.mynet.com:####

**Comment by f0o** [comment]
Hi dedwards,

Proxy has been specified with IP:PORT :/

DNS resolves fine for the vsphere-domain too

**Comment by jessehu** [comment]
Seems https://github.com/vmware/rbvmomi/blob/master/lib/rbvmomi/trivial_soap.rb#L38 needs the caller to set "@opts[:proxyHost], @opts[:proxyPort]". You can try modifying the file vim.rb like this:

vi `gem env gemdir`/gems/rvc-1.8.0/lib/rvc/modules/vim.rb 

      if ENV[:http_proxy]
        http, proxyHost, proxyPort = ENV[:http_proxy].split(':')
        proxyHost = proxyHost[2..-1]
      else
        proxyHost = nil
        proxyPort = nil
      end
      vim = RbVmomi::VIM.new :host => host,
                             :port => port,
                             :path => '/sdk',
                             :ns => 'urn:vim25',
                             :rev => (opts[:rev]||'4.0'),
                             :ssl => true,
                             :insecure => bad_cert, :proxyHost => proxyHost, :proxyPort => proxyPort

I don't have an proxy env in hand, so can not test the code now.
