### ISSUE TITLE
can't connect to vcenter with rvc on vma

### ISSUE THREAD

**Issue by yankeesam** [vmware/rvc#99]
I'm not able to connect to vCenter using rvc on my VMA appliance while I can connect to ESXi host via rvc on same VMA appliance. I don't know what's wrong, I've the correct default identity source set on my SSO but it still doesn't authenticate. Below is the error(replaced username/jostanames) please help:-

# rvc
NameError while loading spbm.rb: uninitialized constant RbVmomi::PBM::PbmCapabilityInstance
/usr/local/rvm/gems/ruby-2.4.1/gems/rbvmomi-1.11.2/lib/rbvmomi/connection.rb:253:in `const_missing'
/usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/lib/rvc/modules/spbm.rb:88:in `load_code'
/usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/lib/rvc/namespace.rb:43:in `instance_eval'
/usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/lib/rvc/namespace.rb:43:in `load_code'
/usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/lib/rvc/namespace.rb:104:in `block in load_module_dir'
/usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/lib/rvc/namespace.rb:92:in `foreach'
/usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/lib/rvc/namespace.rb:92:in `load_module_dir'
/usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/lib/rvc/shell.rb:228:in `block in reload_modules'
/usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/lib/rvc/shell.rb:227:in `each'
/usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/lib/rvc/shell.rb:227:in `reload_modules'
/usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/bin/rvc:63:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.1/bin/rvc:23:in `load'
/usr/local/rvm/gems/ruby-2.4.1/bin/rvc:23:in `<main>'
/usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
Host to connect to (user@host): **username@domainname@hostname**
/usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/lib/rvc/util.rb:62:in `err': invalid URI (RVC::Util::UserError)
        from /usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/lib/rvc/uri_parser.rb:47:in `parse'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/bin/rvc:73:in `block in <top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/bin/rvc:71:in `each'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/rvc-1.8.0/bin/rvc:71:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/rvc:23:in `load'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/rvc:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by shivamvarma** [comment]
Same problem
